version: "3.3"
services:
  nextjs-jest:
    build:
      context: ./nextjs-jest
      dockerfile: Dockerfile
    image: nextjsimg
    container_name: nextjscont
    ports:
      - "3000:3000"
    restart: on-failure
  nodejs-jest:
    build:
      context: ./nodejs-jest
      dockerfile: Dockerfile
    image: nodejsimg
    container_name: nodejscont
    ports:
      - "3001:3000"
    restart: on-failure
