name: Run Node.js Docker Image

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2

    - name: Build Docker image
      run: docker build -t your-docker-repo/your-app:latest .

    - name: Run Docker container
      run: docker run -d your-docker-repo/your-app:latest
